server:
  port: 8080

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/goods_center?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: admin.1234

mybatis:
  # 指定xml文件位置
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 驼峰命名转换
    map-underscore-to-camel-case: true
